// Area light textures
TEXTURE2D_ARRAY(_LtcData); // We pack all Ltc data inside one texture array to limit the number of resource used

#define LTCLIGHTINGMODEL_GGX (0)
#define LTCLIGHTINGMODEL_DISNEY_DIFFUSE (1)
#define LTCLIGHTINGMODEL_CHARLIE (2)
#define LTCLIGHTINGMODEL_FABRIC_LAMBERT (3)
#define LTCLIGHTINGMODEL_KAJIYA_KAY_SPECULAR (4)
#define LTCLIGHTINGMODEL_KAJIYA_KAY_DIFFUSE (5)
#define LTCLIGHTINGMODEL_MARSCHNER (6)
#define LTCLIGHTINGMODEL_COOK_TORRANCE (7)
#define LTCLIGHTINGMODEL_WARD (8)
#define LTCLIGHTINGMODEL_OREN_NAYAR (9)
#define LTCLIGHTINGMODEL_COUNT (10)

#define LTC_LUT_SIZE   64
#define LTC_LUT_SCALE  ((LTC_LUT_SIZE - 1) * rcp(LTC_LUT_SIZE))
#define LTC_LUT_OFFSET (0.5 * rcp(LTC_LUT_SIZE))
